UE4/Abgabe/src/main/java/at/ac/tuwien/big/we16/ue4/model/Product.java
package at.ac.tuwien.big.we16.ue4.model;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import at.ac.tuwien.big.we16.ue4.exception.InvalidBidException;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Entity
public class Product extends AbstractPersistentObject {
    private String name_en;
    private String name_de;
    private String image;
    private String imageAlt;
    private Date auctionEnd;
    private ProductType type;
    private int year;
    private String producer;
    private boolean expired;

    @OneToMany(fetch = FetchType.EAGER)
    private List<RelatedProduct> relatedProducts;

    @OneToMany(fetch = FetchType.EAGER)
    private List<Bid> bids;

    public Product(String name_en, String image, String imageAlt, Date auctionEnd, ProductType type, int year, String producer, List<Bid> bids) {
        this.name_en = name_en;
        this.image = image;
        this.imageAlt = imageAlt;
        this.auctionEnd = auctionEnd;
        this.type = type;
        this.year = year;
        this.producer = producer;
        this.expired = false;
        this.bids = bids;
    }

    public Product() {}

    public void setAllValues(Product product) {
        this.name_en = product.name_en;
        this.name_de = product.name_de;
        this.image = product.image;
        this.imageAlt = product.imageAlt;
        this.auctionEnd = product.auctionEnd;
        this.type = product.type;
        this.year = product.year;
        this.producer = product.producer;
        this.expired = product.expired;
        this.relatedProducts = product.relatedProducts;
        this.bids = product.bids;
    }

    public Bid getHighestBid() {
        Bid highest = null;
        int highestAmount = 0;
        for (Bid bid : this.bids) {
            if (bid.getAmount() > highestAmount) {
                highest = bid;
            }
        }
        return highest;
    }

    public boolean hasAuctionEnded() {
        return this.getAuctionEnd().before(new Date());
    }

    public void addBid(Bid bid) throws InvalidBidException {
        this.bids.add(bid);
    }

    public boolean hasExpired() {
        return expired;
    }

    public void setExpired() {
        this.expired = true;
    }

    public Set<User> getUsers() {
        Set<User> users = new HashSet<>();
        for (Bid bid : this.bids) {
            users.add(bid.getUser());
        }
        return users;
    }

    public boolean hasBids() {
        return this.bids.size() > 0;
    }

    public boolean isValidBidAmount(int amount) {
        return !this.hasBids() || this.getHighestBid().getAmount() < amount;
    }

    public boolean hasBidByUser(User user) {
        for (Bid bid : this.bids) {
            if (bid.getUser().equals(user)) {
                return true;
            }
        }
        return false;
    }

    //getter and setter

    public String getName_en() {
        return name_en;
    }

    public void setName_en(String name_en) {
        this.name_en = name_en;
    }

    public String getName_de() {
        return name_de;
    }

    public void setName_de(String name_de) {
        this.name_de = name_de;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getImageAlt() {
        return imageAlt;
    }

    public void setImageAlt(String imageAlt) {
        this.imageAlt = imageAlt;
    }

    public Date getAuctionEnd() {
        return auctionEnd;
    }

    public void setAuctionEnd(Date auctionEnd) {
        this.auctionEnd = auctionEnd;
    }

    public ProductType getType() {
        return type;
    }

    public void setType(ProductType type) {
        this.type = type;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public String getProducer() {
        return producer;
    }

    public void setProducer(String producer) {
        this.producer = producer;
    }

    public boolean isExpired() {
        return expired;
    }

    public void setExpired(boolean expired) {
        this.expired = expired;
    }

    public List<RelatedProduct> getRelatedProducts() {
        return relatedProducts;
    }

    public void setRelatedProducts(List<RelatedProduct> similarProducts) {
        this.relatedProducts = similarProducts;
    }

    public List<Bid> getBids() {
        return bids;
    }

    public void setBids(List<Bid> bids) {
        this.bids = bids;
    }
}

UE4/Abgabe/src/main/java/at/ac/tuwien/big/we16/ue4/model/User.java
package at.ac.tuwien.big.we16.ue4.model;

import com.sun.istack.internal.NotNull;

import at.ac.tuwien.big.we16.ue4.exception.InvalidBidException;

import org.hibernate.validator.constraints.Email;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import java.util.Date;

@Entity
public class User extends AbstractPersistentObject {

    @NotNull
    private String salutation;
    @NotNull
    private String firstname;
    @NotNull
    private String lastname;
    @Column(unique = true)
    @Email
    private String email;
    @Size(min = 4, max = 12)
    private String password;
    @Temporal(TemporalType.DATE)
    private Date date;

    private int balance;
    private int runningAuctionsCount;
    private int wonAuctionsCount;
    private int lostAuctionsCount;

    public User() {}

    public User(String salutation, String firstname, String lastname, String email, String password, Date date) {
        this.salutation = salutation;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.password = password;
        this.date = date;
        this.balance = 150000;
        this.runningAuctionsCount = 0;
        this.wonAuctionsCount = 0;
        this.lostAuctionsCount = 0;
    }

    public String getFullName() {
        return this.firstname + " " + this.lastname;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return password;
    }

    public float getConvertedBalance() {
        float convertedBalance = (float)this.balance;
        return convertedBalance / 100;
    }

    public void decreaseBalance(int amount) throws InvalidBidException {
        this.balance -= amount;
    }

    public void increaseBalance(int amount) throws InvalidBidException {
        this.balance += amount;
    }

    public int getRunningAuctionsCount() {
        return this.runningAuctionsCount;
    }

    public void incrementRunningAuctions() {
        this.runningAuctionsCount++;
    }

    public void decrementRunningAuctions() {
        this.runningAuctionsCount--;
    }

    public int getWonAuctionsCount() {
        return this.wonAuctionsCount;
    }

    public int getLostAuctionsCount() {
        return this.lostAuctionsCount;
    }

    public void incrementLostAuctionsCount() {
        this.lostAuctionsCount++;
    }

    public void incrementWonAuctionsCount() {
        this.wonAuctionsCount++;
    }

    public boolean hasSufficientBalance(int amount) {
        return this.balance >= amount;
    }

    public String getEmail() {
        return email;
    }

    public String getSalutation() {
        return salutation;
    }

    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
}

UE4/Abgabe/src/main/webapp/views/details.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setBundle basename="messages" />
<jsp:useBean id="product" scope="request" type="at.ac.tuwien.big.we16.ue3.model.Product"/>
<c:set var="localeCode" value="${pageContext.response.locale}" />
<c:choose>
    <c:when test="${localeCode == 'de' }">
        <c:set var="productName" value="${product.name_de}" />
    </c:when>
    <c:otherwise>
        <c:set var="productName" value="${product.name_en}" />
    </c:otherwise>
</c:choose>
<jsp:include page='partials/header.jsp'>
    <jsp:param name="title" value="${productName}" />
    <jsp:param name="showLogout" value="true" />
</jsp:include>
<jsp:include page='partials/sidebar.jsp'/>


<main aria-labelledby="productheadline" class="details-container">
        <div class="details-image-container">
            <img class="details-image" src="/images/${product.image}" alt="${product.imageAlt}">
        </div>
        <div data-product-id="${product.id}" class="details-data">
            <h2 class="main-headline" id="productheadline">${productName}</h2>
            <div class="auction-expired-text" <c:if test="${!product.hasAuctionEnded()}">style="display:none"</c:if>>
                <p>
                    <fmt:message key="details.auctionEnded" />
                    <fmt:message key="details.sold" >
                        <fmt:param>
                            <span class="highest-bid">
                                <c:if test="${product.hasBids()}">
                                    <fmt:formatNumber value="${product.highestBid.convertedAmount}" maxFractionDigits="2" minFractionDigits="2"/> €
                                </c:if>
                            </span>
                        </fmt:param>
                        <fmt:param>
                            <span class="highest-bidder">
                                <c:if test="${product.hasBids()}">
                                    ${product.highestBid.user.fullName}
                                </c:if>
                            </span>
                        </fmt:param>
                    </fmt:message>
                </p>
            </div>
            <c:if test="${!product.hasAuctionEnded()}">
                <p class="detail-time"><fmt:message key="details.remainingTime" />: <span data-end-time="<fmt:formatDate value="${product.auctionEnd}" pattern="yyyy,MM,dd,HH,mm,ss,SSS"/>" class="detail-rest-time js-time-left"></span></p>
                <form class="bid-form" method="post" action="/product/${product.id}/bid">
                    <label class="bid-form-field" id="highest-price">
                        <c:choose>
                            <c:when test="${product.hasBids()}">
                                <span class="highest-bid"><fmt:formatNumber value="${product.highestBid.convertedAmount}" maxFractionDigits="2" minFractionDigits="2"/> €</span>
                                <span class="highest-bidder">${product.highestBid.user.fullName}</span>
                            </c:when>
                            <c:otherwise>
                                <span class="highest-bid"><fmt:message key="details.noBids" /></span>
                                <span class="highest-bidder"></span>
                            </c:otherwise>
                        </c:choose>
                    </label>
                    <label class="accessibility" for="new-price"></label>
                    <input type="number" step="0.01" min="0" id="new-price" class="bid-form-field form-input" name="new-price" required>
                    <p class="bid-error"><fmt:message key="details.bidError" /></p>
                    <input type="submit" id="submit-price" class="bid-form-field button" name="submit-price" value="<fmt:message key="details.submitBid" />">
                </form>
            </c:if>
            <h2 class="sub-main-headline" id="relatedproductsheadline"><fmt:message key="details.relatedProducts" /></h2>
            <ul class="related-products-list">
                <c:forEach items="${product.relatedProducts}" var="relatedProduct">
                    <c:choose>
                        <c:when test="${localeCode == 'de' }">
                            <li>${relatedProduct.name_de}</li>
                        </c:when>
                        <c:otherwise>
                            <li>${relatedProduct.name_en}</li>
                        </c:otherwise>
                    </c:choose>
                </c:forEach>
            </ul>
        </div>
</main>
<jsp:include page='partials/footer.jsp'/>

UE4/Abgabe/src/main/webapp/views/login.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setBundle basename="messages" />
<jsp:useBean id="error" scope="request" type="java.lang.Boolean" />
<fmt:message key="login.headline" var="title"/>
<jsp:include page='partials/header.jsp'>
    <jsp:param name="title" value="${title}" />
    <jsp:param name="showRegistration" value="true" />
</jsp:include>

<main role="main" aria-labelledby="formheadline">
    <form class="form" method="post">
        <h2 id="formheadline" class="registration-headline"><fmt:message key="login.headline" /></h2>
        <c:if test="${error}">
            <p class="error-text">
                <fmt:message key="login.invalidLoginData" />
            </p>
        </c:if>
        <div class="form-row">
            <label class="form-label" for="email-input">
                <fmt:message key="login.email" />
            </label>
            <input type="email" name="email" id="email-input" required class="form-input">
            <span id="email-error" class="error-text"></span>
        </div>
        <div class="form-row">
            <label class="form-label" for="password-input">
                <fmt:message key="login.password" />
            </label>
            <input type="password" name="password" id="password-input" required class="form-input" minlength="4" maxlength="12">
            <span id="password-error" class="error-text"></span>
        </div>
        <div class="form-row form-row-center">
            <button class="button button-submit">
                <fmt:message key="login.login" />
            </button>
        </div>
    </form>
</main>
<jsp:include page='partials/footer.jsp'/>

UE4/Abgabe/src/main/webapp/views/overview.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<jsp:useBean id="products" scope="request" type="java.util.Collection<at.ac.tuwien.big.we16.ue3.model.Product>" />
<jsp:useBean id="user" scope="request" type="at.ac.tuwien.big.we16.ue3.model.User" />
<fmt:setBundle basename="messages" />
<fmt:message key="overview.headline" var="title"/>
<jsp:include page='partials/header.jsp'>
    <jsp:param name="title" value="${title}" />
    <jsp:param name="showLogout" value="true" />
</jsp:include>
<jsp:include page='partials/sidebar.jsp' />
<c:set var="localeCode" value="${pageContext.response.locale}" />

<main role="main" aria-labelledby="productsheadline">
    <h2 class="main-headline" id="productsheadline"><fmt:message key="overview.headline" /></h2>
    <div class="products">
        <c:forEach items="${products}" var="product">
            <div class="product-outer" data-product-id="${product.id}">
                <a href="/product/${product.id}" class="product <c:if test="${product.hasAuctionEnded()}">expired</c:if> <c:if test="${product.highestBid.isBy(user)}">highlight</c:if>" title="<fmt:message key="overview.moreInformation" /> ${product.name_en}">
                    <img class="product-image" src="/images/${product.image}" alt="${product.imageAlt}">
                    <dl class="product-properties properties">
                        <dt><fmt:message key="overview.name" /></dt>
                        <c:choose>
                            <c:when test="${localeCode=='de'}">
                                <dd class="product-name">${product.name_de}</dd>
                            </c:when>
                            <c:otherwise>
                                <dd class="product-name">${product.name_en}</dd>
                            </c:otherwise>
                        </c:choose>
                        <dt><fmt:message key="overview.price" /></dt><dd class="product-price">
                            <c:choose>
                                <c:when test="${product.hasBids()}">
                                    <fmt:formatNumber value="${product.highestBid.convertedAmount}"  maxFractionDigits="2" minFractionDigits="2"/> €
                                </c:when>
                                <c:otherwise>
                                    <span class="no-bids"><fmt:message key="overview.noBids" /></span>
                                </c:otherwise>
                            </c:choose>
                        </dd>
                        <dt><fmt:message key="overview.remainingTime" /></dt><dd data-end-time="<fmt:formatDate value="${product.auctionEnd}" pattern="yyyy,MM,dd,HH,mm,ss,SSS"/>" data-end-text="<fmt:message key="overview.expired" />" class="product-time js-time-left"></dd>
                        <dt><fmt:message key="overview.highestBidder" /></dt><dd class="product-highest">${product.highestBid.user.fullName}</dd>
                    </dl>
                </a>
            </div>
        </c:forEach>
    </div>
</main>
<jsp:include page='partials/footer.jsp' />

UE4/Abgabe/src/main/webapp/views/registration.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<jsp:useBean id="error" scope="request" type="at.ac.tuwien.big.we16.ue3.error.FormError"/>
<fmt:setBundle basename="messages" />
<fmt:message key="registration.registerHeadline" var="title"/>
<jsp:include page='partials/header.jsp'>
    <jsp:param name="title" value="${title}" />
    <jsp:param name="showLogin" value="true" />
</jsp:include>

<main role="main" aria-labelledby="formheadline">
    <form class="form" method="post">
        <h2 id="formheadline" class="registration-headline"><fmt:message key="registration.registerHeadline" /></h2>

        <fieldset>
            <legend><fmt:message key="registration.personalData" /></legend>
            <div class="form-row">
                <label class="form-label" for="salutation-input">
                    <fmt:message key="registration.salutation" /> *
                </label>
                <select name="salutation" id="salutation-input" class="form-input">
                    <option value="ms"><fmt:message key="registration.salutation.ms" /></option>
                    <option value="mr"><fmt:message key="registration.salutation.mr" /></option>
                </select>
            </div>
            <c:if test="${error.titleError}">
                <span id="salutation-error" class="error-text"><fmt:message key="registration.error.mandatory" /></span>
            </c:if>
            <div class="form-row">
                <label class="form-label" for="firstname-input">
                    <fmt:message key="registration.firstname" /> *
                </label>
                <input type="text" name="firstname" id="firstname-input" class="form-input">
            </div>
            <c:if test="${error.firstNameError}">
                <span id="firstname-error" class="error-text"><fmt:message key="registration.error.mandatory" /></span>
            </c:if>
            <div class="form-row">
                <label class="form-label" for="lastname-input">
                    <fmt:message key="registration.lastname" /> *
                </label>
                <input type="text" name="lastname" id="lastname-input" class="form-input">
            </div>
            <c:if test="${error.lastNameError}">
                <span id="lastname-error" class="error-text"><fmt:message key="registration.error.mandatory" /></span>
            </c:if>
            <div class="form-row">
                <label class="form-label" for="dateofbirth-input">
                    <fmt:message key="registration.dateofbirth" /> *
                </label>
                <input type="text" name="dateofbirth" id="dateofbirth-input" class="form-input">
            </div>
            <c:choose>
                <c:when test="${error.dateFormatError}">
                    <span id="date-format-error" class="error-text"><fmt:message key="registration.error.dateFomat" /></span>
                </c:when>
                <c:when test="${error.dateError}">
                    <span id="date-error" class="error-text"><fmt:message key="registration.error.date" /></span>
                </c:when>
            </c:choose>
            <div class="form-row">
                <label class="form-label" for="email-input">
                    <fmt:message key="registration.email" /> *
                </label>
                <input type="text" name="email" id="email-input" class="form-input">
            </div>
            <c:choose>
                <c:when test="${error.mailFormatError}">
                    <span id="email-format-error" class="error-text"><fmt:message key="registration.error.emailFormat" /></span>
                </c:when>
                <c:when test="${error.mailError}">
                    <span id="email-error" class="error-text"><fmt:message key="registration.error.email" /></span>
                </c:when>
            </c:choose>
            <div class="form-row">
                <label class="form-label" for="password-input">
                    <fmt:message key="registration.password" /> *
                </label>
                <input type="password" name="password" id="password-input" class="form-input">
            </div>
            <c:if test="${error.passwordError}">
                <span id="password-error" class="error-text"><fmt:message key="registration.error.password" /></span>
            </c:if>
        </fieldset>

        <fieldset>
            <legend><fmt:message key="registration.shippingaddress" /></legend>
            <div class="form-row">
                <label class="form-label" for="streetAndNumber-input">
                    <fmt:message key="registration.streetAndNumber" />
                </label>
                <input type="text" name="streetAndNumber" id="streetAndNumber-input" class="form-input">
            </div>
            <div class="form-row">
                <label class="form-label" for="postcodeAndCity-input">
                    <fmt:message key="registration.postcodeAndCity" />
                </label>
                <input type="text" name="postcodeAndCity" id="postcodeAndCity-input" class="form-input">
            </div>
            <div class="form-row">
                <label class="form-label" for="country-input">
                    <fmt:message key="registration.country" />
                </label>
                <select name="country" id="country-input" class="form-input">
                    <option value="at"><fmt:message key="registration.country.at" /></option>
                    <option value="de"><fmt:message key="registration.country.de" /></option>
                    <option value="ch"><fmt:message key="registration.country.ch" /></option>
                </select>
            </div>
        </fieldset>

        <div class="form-row form-row-center">
            <p>
                <label for="terms">
                    <input type="checkbox" name="terms" id="terms" required onchange="isFormValid()">
                    <fmt:message key="registration.acceptTerms" /> *
                </label>
            </p>
        </div>
        <div class="form-row form-row-center">
            <button class="button button-submit register-button">
                <fmt:message key="registration.register" />
            </button>
        </div>
        <div class="form-row form-row-center">
            <p>
                <fmt:message key="registration.compulsoryFields" />
            </p>
        </div>
    </form>
</main>

<jsp:include page='partials/footer.jsp'/>